services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: sqlite:////app/data/emobot.db
    ports:
      - "8000:8000"
    volumes:
      - ./database-data:/app/data
